backbone: resnet18
backbone_kwargs: null
head: linear
labels:
- ants
- bees
learning_rate: null
loss_fn: null
lr_scheduler: null
metrics: null
multi_label: false
num_classes: null
optimizer: Adam
pretrained: true
training_strategy: default
training_strategy_kwargs: null
